import { describe, it, expect, beforeAll, vi } from 'vitest';

// Header transitively imports lib/auth.ts, which opens a live bun:sqlite
// connection at module-load time — mock it out so this jsdom test doesn't
// depend on the real DB.
vi.mock('@/components/Header', () => ({
  Header: () => null,
}));

describe('RootLayout', () => {
  let RootLayout: any;
  let metadata: any;

  beforeAll(async () => {
    const module = await import('@/app/layout');
    RootLayout = module.default;
    metadata = module.metadata;
  });

  it('layout module exports a default function', () => {
    expect(typeof RootLayout).toBe('function');
  });

  it('layout module exports metadata', () => {
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('metadata has correct title', () => {
    expect(metadata.title).toBe('Create Next App');
  });

  it('metadata has correct description', () => {
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('metadata object structure is valid', () => {
    expect(Object.keys(metadata)).toContain('title');
    expect(Object.keys(metadata)).toContain('description');
  });

  it('metadata title is a string', () => {
    expect(typeof metadata.title).toBe('string');
  });

  it('metadata description is a string', () => {
    expect(typeof metadata.description).toBe('string');
  });

  it('metadata has both title and description properties', () => {
    expect('title' in metadata).toBe(true);
    expect('description' in metadata).toBe(true);
  });

  it('layout is a named export', () => {
    expect(RootLayout).not.toBeUndefined();
  });

  it('layout function has required parameters', () => {
    expect(RootLayout.length).toBeGreaterThanOrEqual(0);
  });

  it('layout function returns JSX element when called', () => {
    const children = <div>Test</div>;
    const result = RootLayout({ children });
    expect(result).toBeDefined();
    expect(result.type).toBe('html');
  });

  it('layout returns element with correct lang attribute', () => {
    const children = <div>Test</div>;
    const result = RootLayout({ children });
    expect(result.props.lang).toBe('en');
  });

  it('layout returns element with body child', () => {
    const children = <div>Test</div>;
    const result = RootLayout({ children });
    expect(result.props.children).toBeDefined();
    expect(result.props.children.type).toBe('body');
  });

  it('layout passes children to body element', () => {
    const children = <div data-testid="test">Test Content</div>;
    const result = RootLayout({ children });
    const bodyProps = result.props.children.props;
    expect(bodyProps.children).toContain(children);
  });
});






